class parse_table:
    parse_dictionary = {
        'Program' : {
            ';' : '',
            'break' : [('Statements','NT')],
            'continue' : [('Statements','NT')],
            'ID' : [('Statements','NT')],
            '=' : '',
            '[' : '',
            ']' : '',
            '(' : '',
            ')' : '',
            ',' : '',
            'global' : [('Statements','NT')],
            'return' : [('Statements','NT')],
            'def' : [('Statements','NT')],
            ':' : '',
            'if' : [('Statements','NT')],
            'else' : '',
            'while' : [('Statements','NT')],
            '==' : '',
            '<' : '',
            '+' : '',
            '-' : '',
            '*' : '',
            '**' : '',
            'NUMBER' : '',
            '$' : [('Statements','NT')]
        },

        'Statements': {
            ';': 'EPSILON',
            'break': [('Statement','NT'), (';','T'), ('Statements','NT')],
            'continue': [('Statement','NT'), (';','T'), ('Statements','NT')],
            'ID': [('Statement','NT'), (';','T'), ('Statements','NT')],
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': [('Statement','NT'), (';','T'), ('Statements','NT')],
            'return': [('Statement','NT'), (';','T'), ('Statements','NT')],
            'def': [('Statement','NT'), (';','T'), ('Statements','NT')],
            ':': '',
            'if': [('Statement','NT'), (';','T'), ('Statements','NT')],
            'else': 'EPSILON',
            'while': [('Statement','NT'), (';','T'), ('Statements','NT')],
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': 'EPSILON'
        },

        'Simple_stmt': {
            ';': 'SYNCH',
            'break': [('break','T')],
            'continue': [('continue','T')],
            'ID': [('Assignment_Call','NT')],
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': [('Global_stmt','NT')],
            'return': [('Return_stmt','NT')],
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Statement': {
            ';': 'SYNCH',
            'break': [('Simple_stmt','NT')],
            'continue': [('Simple_stmt','NT')],
            'ID': [('Simple_stmt','NT')],
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': [('Simple_stmt','NT')],
            'return': [('Simple_stmt','NT')],
            'def': [('Compound_stmt','NT')],
            ':': '',
            'if': [('Compound_stmt','NT')],
            'else': '',
            'while': [('Compound_stmt','NT')],
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Compound_stmt': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': '',
            'return': '',
            'def': [('Function_def','NT')],
            ':': '',
            'if': [('If_stmt','NT')],
            'else': '',
            'while': [('Iteration_stmt','NT')],
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Assignment_Call': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': [('ID','T'), ('B','NT')],
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'B': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': '',
            '=': [('=', 'T'), ('C','NT')],
            '[': [('[','T'), ('Expression','NT'), (']','T'), ('=','T'), ('C','NT')],
            ']': '',
            '(': [('(','T'), ('Arguments','NT'), (')','T')],
            ')': '',
            ',': '',
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'C': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': [('Expression','NT')],
            '=': '',
            '[': [('[','T'), ('Expression','NT'), ('List_Rest','NT'), (']','T')],
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': [('Expression','NT')],
            '$': ''
        },

        'List_Rest': {
            ';': '',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': 'EPSILON',
            '(': '',
            ')': '',
            ',': [(',','T'), ('Expression','NT'), ('List_Rest','NT')],
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Return_stmt': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': '',
            'return': [('return','T'), ('Return_Value','NT')],
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Return_Value': {
            ';': 'EPSILON',
            'break': '',
            'continue': '',
            'ID': [('Expression','NT')],
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': [('Expression','NT')],
            '$': ''
        },

        'Global_stmt': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': [('global','T'), ('ID','T')],
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Function_def': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': '',
            'return': '',
            'def': [('def','T'), ('ID','T'), ('(','T'), ('Params','NT'), (')','T'), (':','T'), ('Statements','NT')],
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Params': {
            ';': '',
            'break': '',
            'continue': '',
            'ID': [('ID','T'), ('Params_Prime','NT')],
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': 'EPSILON',
            ',': '',
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Params_Prime': {
            ';': '',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': 'EPSILON',
            ',': [(',','T'), ('ID','T'), ('Params_Prime','NT')],
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'If_stmt': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': [('if','T'), ('Relational_Expression','NT'), (':','T'), ('Statements','NT'), ('Else_block','NT')],
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Else_block': {
            ';': 'EPSILON',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': [('else','T'), (':','T'), ('Statements','NT')],
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Iteration_stmt': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': [('while','T'), ('(','T'), ('Relational_Expression','NT'), (')','T'), ('Statements','NT')],
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },
        'Relational_Expression': {
            ';': '',
            'break': '',
            'continue': '',
            'ID': [('Expression','NT'), ('Relop','NT'), ('Expression','NT')],
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': 'SYNCH',
            ',': '',
            'global': '',
            'return': '',
            'def': '',
            ':': 'SYNCH',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': ['Expression', 'Relop', 'Expression'],
            '$': ''
        },
        'Relop': {
            ';': '',
            'break': '',
            'continue': '',
            'ID': 'SYNCH',
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': '',
            ',': '',
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': [('==','T')],
            '<': [('<','T')],
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': 'SYNCH',
            '$': ''
        },
        'Expression': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': [('Term','NT'), ('Expression_Prime','NT')],
            '=': '',
            '[': '',
            ']': 'SYNCH',
            '(': '',
            ')': 'SYNCH',
            ',': 'SYNCH',
            'global': '',
            'return': '',
            'def': '',
            ':': 'SYNCH',
            'if': '',
            'else': '',
            'while': '',
            '==': 'SYNCH',
            '<': 'SYNCH',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': [('Term','NT'), ('Expression_Prime','NT')],
            '$': ''
        },
        'Expression_Prime': {
            ';': 'EPSILON',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': 'EPSILON',
            '(': '',
            ')': 'EPSILON',
            ',': 'EPSILON',
            'global': '',
            'return': '',
            'def': '',
            ':': 'EPSILON',
            'if': '',
            'else': '',
            'while': '',
            '==': 'EPSILON',
            '<': 'EPSILON',
            '+': [('+','T'), ('Term','NT'), ('Expression_Prime','NT')],
            '-': [('-','T'), ('Term','NT'), ('Expression_Prime','NT')],
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },
        'Term': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': [('Factor','NT'), ('Term_Prime','NT')],
            '=': '',
            '[': '',
            ']': 'SYNCH',
            '(': '',
            ')': 'SYNCH',
            ',': 'SYNCH',
            'global': '',
            'return': '',
            'def': '',
            ':': 'SYNCH',
            'if': '',
            'else': '',
            'while': '',
            '==': 'SYNCH',
            '<': 'SYNCH',
            '+': 'SYNCH',
            '-': 'SYNCH',
            '*': '',
            '**': '',
            'NUMBER': [('Factor','NT'), ('Term_Prime','NT')],
            '$': ''
        },
        'Term_Prime': {
            ';': 'EPSILON',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': 'EPSILON',
            '(': '',
            ')': 'EPSILON',
            ',': 'EPSILON',
            'global': '',
            'return': '',
            'def': '',
            ':': 'EPSILON',
            'if': '',
            'else': '',
            'while': '',
            '==': 'EPSILON',
            '<': 'EPSILON',
            '+': 'EPSILON',
            '-': 'EPSILON',
            '*': [('*','T'), ('Factor','NT'), ('Term_Prime','NT')],
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Factor': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': [('Atom','NT'), ('Power','NT')],
            '=': '',
            '[': '',
            ']': 'SYNCH',
            '(': '',
            ')': 'SYNCH',
            ',': 'SYNCH',
            'global': '',
            'return': '',
            'def': '',
            ':': 'SYNCH',
            'if': '',
            'else': '',
            'while': '',
            '==': 'SYNCH',
            '<': 'SYNCH',
            '+': 'SYNCH',
            '-': 'SYNCH',
            '*': 'SYNCH',
            '**': '',
            'NUMBER': [('Atom','NT'), ('Power','NT')],
            '$': ''
        },
        'Power': {
            ';': [('Primary','NT')],
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': [('Primary','NT')],
            ']': [('Primary','NT')],
            '(': [('Primary','NT')],
            ')': [('Primary','NT')],
            ',': [('Primary','NT')],
            'global': '',
            'return': '',
            'def': '',
            ':': [('Primary','NT')],
            'if': '',
            'else': '',
            'while': '',
            '==': [('Primary','NT')],
            '<': [('Primary','NT')],
            '+': [('Primary','NT')],
            '-': [('Primary','NT')],
            '*': [('Primary','NT')],
            '**': [('**','T'), ('Factor','NT')],
            'NUMBER': '',
            '$': ''
        },
        'Primary': {
            ';': 'EPSILON',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': [('[','T'), ('Expression','NT'), (']','T'), ('Primary','NT')],
            ']': 'EPSILON',
            '(': [('(','T'), ('Arguments','NT'), (')','T'), ('Primary','NT')],
            ')': 'EPSILON',
            ',': 'EPSILON',
            'global': '',
            'return': '',
            'def': '',
            ':': 'EPSILON',
            'if': '',
            'else': '',
            'while': '',
            '==': 'EPSILON',
            '<': 'EPSILON',
            '+': 'EPSILON',
            '-': 'EPSILON',
            '*': 'EPSILON',
            '**': '',
            'NUMBER': '',
            '$': ''
        },

        'Arguments': {
            ';': '',
            'break': '',
            'continue': '',
            'ID': [('Expression','NT'), ('Arguments_Prime','NT')],
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': 'EPSILON',
            ',': '',
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': [('Expression','NT'), ('Arguments_Prime','NT')],
            '$': ''
        },
        'Arguments_Prime': {
            ';': '',
            'break': '',
            'continue': '',
            'ID': '',
            '=': '',
            '[': '',
            ']': '',
            '(': '',
            ')': 'EPSILON',
            ',': [(',','T'), ('Expression','NT'), ('Arguments_Prime','NT')],
            'global': '',
            'return': '',
            'def': '',
            ':': '',
            'if': '',
            'else': '',
            'while': '',
            '==': '',
            '<': '',
            '+': '',
            '-': '',
            '*': '',
            '**': '',
            'NUMBER': '',
            '$': ''
        },
        'Atom': {
            ';': 'SYNCH',
            'break': '',
            'continue': '',
            'ID': [('ID','T')],
            '=': '',
            '[': 'SYNCH',
            ']': 'SYNCH',
            '(': 'SYNCH',
            ')': 'SYNCH',
            ',': 'SYNCH',
            'global': '',
            'return': '',
            'def': '',
            ':': 'SYNCH',
            'if': '',
            'else': '',
            'while': '',
            '==': 'SYNCH',
            '<': 'SYNCH',
            '+': 'SYNCH',
            '-': 'SYNCH',
            '*': 'SYNCH',
            '**': 'SYNCH',
            'NUMBER': [('NUMBER','T')],
            '$': ''
        }
    }

    def parse(self, nt, t):
        print(f'elements are {nt} and {t}')
        return self.parse_dictionary[nt][t]